### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by phuze** [lifo101/php-daemon#10]
Do you have any links to good reads for understanding the logic behind your daemon?

Maybe I don't understand the concept of a daemon, but I just don't get how to use things here. For example, you can define the max number of workers to fork via 'setMaxProcesses':

```
$this->addWorker('myWorker', 'example')
            ->setAutoRestart(true)  # enable auto-restarts of workers, to show them exit and be re-created on-the-fly
            ->setMaxCalls(10)       # how many calls a worker will process before exiting
            ->setMaxRuntime(10)     # how long a worker will run before exiting
            ->setMaxProcesses(3);    # how many workers to fork
```

But i'm not understanding what that actually does?

Say for example, I have a bucket of 12 apples. I have a worker which eats apples, one at a time. I would assume, by defining that 3 workers should be created on each loop, then 3 apples would be eaten every loop. This is not the behavior I'm seeing. I can fork 30 processes, but only 1 apple ever gets eaten each iteration.

You also note in your documentation that you can call a task from a worker, but I have found no examples and cannot figure out how to make that happen.

I could use some help in understanding all this and I'd very much appreciate any info or links you can provide.

[b]Edit:[/b] Also, is it necessary to use the `example.php` file? How do I start up this daemon without having to login to the server, execute: `php example.php mySampleDaemon` then leaving terminal open?

Thank you.

**Comment by lifo101** [comment]
Did you read any of the wiki? I go over [Workers ](https://github.com/lifo101/php-daemon/wiki/Workers) and [Tasks](https://github.com/lifo101/php-daemon/wiki/Tasks), etc.

A worker is basically a wrapper around 1 or more sub-processes that are automatically forked for you in the background. Every time you call a method on your worker it'll fork that method call into a background process and eventually return the result to your main daemon process.

So, if your worker is eating apples and you have a maximum of 3 processes allowed, that means you can have, at most, 3 apples being eaten at any given moment, it doesn't guarantee that you'll eat 3 apples each loop cycle. That depends on the OS, and how long it takes each background process to eat an apple.

Those functions `setMaxProcesses`, `setMaxRuntime` and `setMaxCalls` are just ways to limit how long your worker sub-processes will hang around before exiting (and having its sub-process cleaned up).  Having a worker sit idle takes up memory, but having to spawn a new worker over and over takes a lot of CPU. So, it's a balancing act based on your personal daemon's requirements.

You don't really want to call a "task" from within a worker, since a task spawns another process it'll most likely cause problems with ProcessManager that is maintaining all of the sub-processes for your daemon. All spawning should be done within the main process of your daemon.  But, honestly, I'm not sure what will happen if you do.

Opening a task is the same as a worker, the only difference is a task does not return anything to the main process.

The `examples.php' file is just there to help users run the included example scripts. You need to make your own 'entry' script that starts your personal daemon as you see fit.

And finally, just to be clear, if you want to run a daemon and have it disconnect from your terminal, you need to set the `setDaemonize(true)` on your daemon. It'll run in the background until it dies or you 'kill -INT {pid}' on the process ID.

**Comment by phuze** [comment]
I did, though admittedly I am having difficulty wrapping my head around it which is why I reached out. I have almost no experience with multiprocessing or daemons as a whole, so the concepts and terminology is new to me. I have a goal, I know I want to utilize your work and I really appreciate you taking the time to help me out, this definitely clarifies some things for me.

My goal is to use your library to build a daemon that will monitor an Azure message queue and spawn various workers to handle those messages -- namely resulting in the management of a database.

I opted for your library, over the standard cron job approach, as I wanted a means of actively monitoring the queue and reacting as things arrive in the queue.

Using the examples you provided in your library, I managed to get a running daemon but it only processes 1 job every loop. I am now trying to figure out how to get things happening concurrently so as to process say 5 jobs on every loop.

Everything you noted above has certainly helped to clarify that and i'll be plugging away more when I return home from work.

Cheers :)

**Comment by lifo101** [comment]
By default, the daemon runs the loop at 1 second intervals. You could speed up the interval, or poll for more events within a single loop iteration. If you spend too much time polling in each iteration the rest of your daemon will suffer. So, try not spend more than 1 second at a time in the `execute` loop.

for example, your `execute` loop could do something like this:

```php
// collect messages for up to 0.8 seconds before exiting
$start = microtime(true);
while (microtime(true) - $start < 0.8 && null !== $m = $this->getNextMessage()) {
  // keep track what messages are being worked on, 
  // so we know what to do when a worker returns a result
  $this->messages[$m->id] = $m; 
  $this->worker('worker')->processMessage($m)->then(function($m) { 
    unset($this->messages[$m->id]);
    $this->log('Message %d processed', $m->id);
  });
}
```

note, in this example I track what messages have been sent to workers so that if the deamon shuts down prematurely I can act on those messages in some way (in the Daemon::onShutdown method; which I don't show here).

You could also just speed up the loop interval with `Daemon::setLoopInterval()` and have it run every 0.5 seconds, or something and only poll for 1 message at a time. Setting it too low will also make your daemon spike CPU too high. It's a balancing act, based on your application requirements.

Either way, even if you're only polling a single message in each loop, remember that the actual work is being done in another process, in parallel to your main process. As soon as you call that `$this->worker('...')` method it returns instantly.

One thing to be aware of. The daemon is not really meant for high-speed processing. The 'calling' mechanism in the back-end that communicates with sub-processes can sometimes break if you make too many calls too quickly. A few messages per second is fine, but hundreds per second will start to become unstable, most likely. I've never tested how much I could do within workers.

**Comment by phuze** [comment]
Just want to express my thanks for taking time out to help me @lifo101 . Your posts played a large part in helping me to understand your library and get the ball rolling. After having spent the past few weeks using it, I can truly appreciate the effort you must have put into crafting this library -- it definitely shows. Amazing work my friend and I thank you for it!

**Comment by lifo101** [comment]
Glad you got use out of the library. Thanks.
