### ISSUE TITLE
Arguments to Tasks

### ISSUE THREAD

**Issue by phuze** [lifo101/php-daemon#13]
I don't get it. https://github.com/lifo101/php-daemon/wiki/Tasks

> Any extra arguments given to Daemon::task($task, [$arg1, $arg2, ...]) will be passed to the Task::run()

How do you consume the argument?

```
protected function execute()
{
     $this->task('Tester', ['JustTesting']);
}
```

```
class Tester extends AbstractTask
{
    use \Lifo\Daemon\LogTrait;

    public function run()
    {
        $this->log('I WANT TO CONSUME THE PASSED ARGUEMENT', getmypid());
    }

}
```

**Comment by lifo101** [comment]
When you call `Daemon::task($task, [$arg1, $arg2, ...])` the $arg1, $arg2, etc are passed as arguments to the task run method. So your run method would look like this:

```php
    public function run($arg1, $arg2)
    {
      // ...
    }
```

Note, in your example above, you are literally passing `['JustTesting']` to the task. This means you're passing an array with the string "JustTesting" to the task. Unless, you are intending to pass an array to your task, you do not need to enclose your arguments in array brackets.

For example:
```php
protected function execute()
{
     $this->task('Tester', 'arg1', 'arg2');
}
```

Alternatively, if you want to create a Task object, you can pass the arguments to the constructor instead of the task method. It all depends on what is best for your code.

```php
$this->task(new Tester($arg1, $arg2));

class Tester {
  public function __construct($arg1, $arg2) {
    $this->arg1 = $arg1; 
    $this->arg2 = $arg2;
  }

  public function run() {
    // do stuff with $this->arg1, etc...
  }
}
```

**Comment by phuze** [comment]
Hmm. That's what I initially tried:

```
protected function execute()
{
     $this->task('Tester', '1');
}
```

```
class Tester extends AbstractTask
{
    use \Lifo\Daemon\LogTrait;

    public function run($test)
    {
        $this->log($test, getmypid());
    }

}
```

But I received this error:

`PHP Fatal error:  Declaration of Tester::run($test) must be compatible with Lifo\Daemon\Task\TaskInterface::run() in /var/www/api/daemons/PriceUpdate/Tester.php on line 5`

**Comment by lifo101** [comment]
I just realized the `TaskInterface` is going to limit the method signature to have no arguments. One way around this is to use the `$args = func_get_args()` within your `run` method to fetch the arguments passed in. Otherwise, use one of the other methods outlined in the docs or what I said previously by passing arguments to the constructor.

_I'll have to update the documentation regarding the run arguments._

**Comment by phuze** [comment]
`$args = func_get_args()` Works great :) Thanks mate.
