### ISSUE TITLE
Premature worker death

### ISSUE THREAD

**Issue by wolverline** [lifo101/php-daemon#19]
I found a log during a daemon worker is running. There was no child worker proc and I don't know where to look and what it means.

`2018-09-11 04:22:06.3434: 4192  DEBUG: Mediator [wcm-crawl-worker]: Premature worker death was reaped [PID=9600] [Call=96] [Status=CALLED]`

**Comment by lifo101** [comment]
Your worker died before the `ProcessManager` could track it's status. But, this is just a debug event. The Promise for the dead worker would still have fired , and so theoretically, your daemon code could have acted on it (via the 'otherwise' callback of the [Promise](../wiki/Workers#example), or via the [ON_RETURN callback](../wiki/Workers#return-value), if you defined that in your code.
