### ISSUE TITLE
calling a task leaves a defunct process when complete.

### ISSUE THREAD

**Issue by muffettsman** [lifo101/php-daemon#2]
I'm still learning how to use php-daemon so i'm sure this is end user error but it seems every time a task completes its process remains open as a zombie 

`	dsmith   32020 32015  0 16:06 pts/9    00:00:02 [php] <defunct>`
I verified from the log that those are the same process ID's from the tasks:
![image](https://user-images.githubusercontent.com/10503885/30298026-78e04f5e-970f-11e7-9d5d-1875a2f31c02.png)

This is how i'm calling the task in my class file:

`	
	  public function execute() {
	  // no args.....
	  // $this->task([$this, 'doTask']);
	  $arg1 = 12;
	  $arg2 = 21;

	  $this->task([$this, 'hitbtcInsert'],0); // arg is which api loop to run... 0 - # of api keys in db.
	  $this->task([$this, 'hitbtcInsert'],1); // arg is which api loop to run... 0 - # of api keys in db.
	  $this->task([$this, 'hitbtcInsert'],2); // arg is which api loop to run... 0 - # of api keys in db.
	  
	  

	  }
`

and the test script that starts it all:

`
	  <?php

	  require __DIR__ . '/vendor/autoload.php';
	  include 'HitbtcInsertDaemon.php';

	  declare(ticks = 1); // needed for signal handling

	  HitbtcInsertDaemon::getInstance()
	    ->setDaemonize(false) 
	    ->setLoopInterval(60)
	    ->setVerbose(true)
	    ->setDebug(true)
	    ->setDebugLevel(3)
	    ->setLogFile('daemon_hitbtc_insert.log')
	    ->run();
`

**Comment by muffettsman** [comment]
(In case anyone else runs into this problem)
with a bit of tinkering figured it out....

need to call the the daemon like this:


```
<?php

require __DIR__ . '/vendor/autoload.php';
include 'HitbtcInsertDaemonWorker.php';

// needed for signal handling (so ^C will be captured and exit the daemon)
declare(ticks = 1);


// run the daemon (`setVerbose` is called so we can see something for the test)
HitbtcInsertDaemon::getInstance()->setVerbose(true)->run();
```

**Comment by lifo101** [comment]
What was the actual problem? The only thing I see you doing differently in your last example was including the `HitbtcInsertDaemonWorker` class? That doesn't make sense to me since the autoloader should do that for you automatically, assuming you used proper name spacing.

**Comment by muffettsman** [comment]
I thought the main problem would be if you are running a daemon that spawns multiple tasks constantly then eventually (or rather quickly) the whole process list table.  Once the process table is full -of regular and zombie processes-, no new -regular- process can be created, even if the system has enough resources -memory, processor, etc.-. The only lacking resource is just a single entry in the process table... It's ok though as I've found I really need a worker as tasks seem to be like a faster cron (will run more even before the first task is finished) so now I'm trying to debug why my task that runs fine won't run more than once as a worker

**Comment by lifo101** [comment]
Gotcha. You are correct. Task's are meant for quick actions when you don't
care as much about the outcome and don't want to block the program flow
(like sending an email). If you need to lots of work over and over then you
definitely want a `Worker` since Workers share a queue you can call your
worker method repeatedly to process lots of little actions all at the same
time.

Look at the worker examples in the code. Your worker should simply just be
an object with some public methods available. And your main daemon loop
should be calling those public methods.

Note, if you're really doing tons of calls per second you might end up
filling up the queue and crash the deamon. So be mindful if what you're
doing. If this is the case you'll have to re-evaluate what you're doing and
refactor.


-- Jason
